[build]
# Default target for iOS simulator
target = "aarch64-apple-ios-sim"
# Allow implicit autoref for local bevy development
rustflags = ["-A", "dangerous_implicit_autorefs"]

[target.aarch64-apple-ios-sim]
# No custom runner needed - build.rs handles simulator deployment
# Direct simulator execution happens automatically during build

[target.aarch64-apple-ios]
# iOS Device runner (when connected) - NO SHELL SCRIPTS
runner = [
    "echo", "📱 iOS Device deployment not configured - use Xcode or ios-deploy"
]
